#!/bin/bash
#menu section
echo -e "Menu"
echo -e "===="
echo -e ""
echo -e "   Command            Description"
echo -e "   -------            -----------"
echo -e "   usernew            Create New Account"
echo -e "   trial              Create 24hours Trial Account"
echo -e "   delete             Terminate account access"
echo -e "   check              Check account login"
echo -e "   member             List all member"
echo -e "   restart            Restart dropbear, webmin, squid3, OpenVPN, and SSH service"
echo -e "   reboot             Reboot virtual server"
echo -e "   speedtest          Perform server bandwidth speedtest"
echo -e "   info               System Information"
echo -e "   about              Autoscript Information"
echo -e "   exit               Exit remote server connection"
